from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

SERVER_NAME = "qgis"
MANAGED_BEGIN = "# BEGIN QGIS Agent MCP (managed automatically)"
MANAGED_END = "# END QGIS Agent MCP"


class OnboardingError(RuntimeError):
    pass


@dataclass(frozen=True)
class CommandResult:
    returncode: int
    stdout: str
    stderr: str


class CommandRunner:
    def run(self, command, input_text=None, timeout=30, event_pump=None):
        command = [str(item) for item in command]
        if event_pump is not None:
            return self._run_with_event_pump(
                command, input_text, timeout, event_pump
            )
        try:
            completed = subprocess.run(
                command,
                input=input_text,
                text=True,
                capture_output=True,
                timeout=timeout,
                check=False,
                creationflags=(
                    subprocess.CREATE_NO_WINDOW
                    if os.name == "nt" and hasattr(subprocess, "CREATE_NO_WINDOW")
                    else 0
                ),
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return CommandResult(-1, "", str(exc))
        return CommandResult(
            completed.returncode, completed.stdout or "", completed.stderr or ""
        )

    @staticmethod
    def _run_with_event_pump(command, input_text, timeout, event_pump):
        try:
            process = subprocess.Popen(
                command,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                creationflags=(
                    subprocess.CREATE_NO_WINDOW
                    if os.name == "nt" and hasattr(subprocess, "CREATE_NO_WINDOW")
                    else 0
                ),
            )
        except OSError as exc:
            return CommandResult(-1, "", str(exc))
        deadline = time.monotonic() + float(timeout)
        first_attempt = True
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                process.kill()
                stdout, stderr = process.communicate()
                message = "Command timed out after {} seconds".format(timeout)
                return CommandResult(-1, stdout or "", (stderr or "") + message)
            try:
                stdout, stderr = process.communicate(
                    input=input_text if first_attempt else None,
                    timeout=min(0.05, remaining),
                )
                return CommandResult(
                    process.returncode, stdout or "", stderr or ""
                )
            except subprocess.TimeoutExpired:
                first_attempt = False
                event_pump()


@dataclass(frozen=True)
class LauncherSpec:
    command: str
    args: tuple
    launcher_path: str
    server_root: str

    def command_line(self):
        return [self.command] + list(self.args)

    def mcp_server(self):
        return {
            "type": "stdio",
            "command": self.command,
            "args": list(self.args),
            "env": {},
        }


class RuntimeManager:
    """Installs a stable launcher script for the server bundled in the plugin."""

    def __init__(
        self,
        plugin_dir,
        qgis_prefix=None,
        home=None,
        python_executable=None,
        runner=None,
    ):
        self.plugin_dir = Path(plugin_dir).resolve()
        self.server_root = self.plugin_dir / "_server"
        self.qgis_prefix = Path(qgis_prefix).resolve() if qgis_prefix else None
        self.home = Path(home).expanduser() if home else Path.home()
        self.python_executable = python_executable
        self.runner = runner or CommandRunner()

    @property
    def launcher_path(self):
        return self.home / ".qgis-mcp" / "bin" / "qgis_mcp_launcher.py"

    def ensure(self):
        main_module = self.server_root / "qgis_mcp" / "__main__.py"
        if not main_module.is_file():
            raise OnboardingError(
                "The MCP runtime is not bundled with this plugin installation. "
                "Reinstall QGIS Agent MCP from an official package."
            )
        python = self._find_python()
        launcher = self.launcher_path
        launcher.parent.mkdir(parents=True, exist_ok=True)
        source = (
            "# Generated by QGIS Agent MCP. Do not edit.\n"
            "import runpy\n"
            "import sys\n"
            "server_root = {!r}\n"
            "if server_root not in sys.path:\n"
            "    sys.path.insert(0, server_root)\n"
            "runpy.run_module('qgis_mcp', run_name='__main__')\n"
        ).format(str(self.server_root))
        _atomic_write(launcher, source)
        spec = LauncherSpec(
            command=str(python),
            args=(str(launcher),),
            launcher_path=str(launcher),
            server_root=str(self.server_root),
        )
        probe = self.runner.run(spec.command_line() + ["--help"], timeout=15)
        if probe.returncode != 0:
            raise OnboardingError(
                "The bundled MCP launcher could not start with {}: {}".format(
                    python, _result_message(probe)
                )
            )
        return spec

    def _find_python(self):
        candidates = []
        configured = self.python_executable or os.environ.get(
            "QGIS_MCP_LAUNCHER_PYTHON"
        )
        if configured:
            candidates.append(Path(configured))
        executable = Path(sys.executable)
        if executable.stem.casefold().startswith("python"):
            candidates.append(executable)
        if self.qgis_prefix:
            roots = [self.qgis_prefix]
            roots.extend(list(self.qgis_prefix.parents)[:3])
            for root in roots:
                candidates.extend(root.glob("apps/Python*/python.exe"))
                candidates.extend(root.glob("bin/python3"))
        for name in ("python3", "python"):
            found = shutil.which(name)
            if found:
                candidates.append(Path(found))
        seen = set()
        for candidate in candidates:
            key = str(candidate).casefold()
            if key in seen or not candidate.is_file():
                continue
            seen.add(key)
            probe = self.runner.run(
                [
                    str(candidate),
                    "-I",
                    "-c",
                    "import sys; print('%s.%s' % sys.version_info[:2])",
                ],
                timeout=10,
            )
            if probe.returncode != 0:
                continue
            try:
                major, minor = [int(value) for value in probe.stdout.strip().split(".")[:2]]
            except (TypeError, ValueError):
                continue
            if (major, minor) >= (3, 10):
                return candidate.resolve()
        raise OnboardingError(
            "No compatible Python 3.10+ runtime was found. Install the standalone "
            "QGIS MCP launcher or set QGIS_MCP_LAUNCHER_PYTHON."
        )


class CodexConnector:
    name = "Codex"

    def __init__(self, home=None):
        self.home = Path(home).expanduser() if home else Path.home()
        self.config_path = self.home / ".codex" / "config.toml"

    def detected(self):
        return bool(shutil.which("codex")) or self.config_path.parent.exists()

    def status(self):
        if not self.config_path.is_file():
            return "not_configured"
        text = self.config_path.read_text(encoding="utf-8")
        return "configured" if MANAGED_BEGIN in text else "not_configured"

    def install(self, spec):
        command = _toml_string(spec.command)
        args = ", ".join(_toml_string(item) for item in spec.args)
        block = (
            "{}\n"
            "[mcp_servers.{}]\n"
            "command = {}\n"
            "args = [{}]\n"
            "{}"
        ).format(MANAGED_BEGIN, SERVER_NAME, command, args, MANAGED_END)
        _update_codex_config(self.config_path, block)
        return (
            "Codex configured for the current user. Restart the Codex app, CLI, "
            "or IDE extension if it is already open."
        )

    def remove(self):
        if not self.config_path.is_file():
            return "Codex was not configured."
        text = self.config_path.read_text(encoding="utf-8")
        updated = _remove_managed_block(text)
        if updated == text:
            return "No QGIS-managed Codex configuration was found."
        _backup_and_write(self.config_path, updated)
        return "QGIS MCP was removed from Codex."


class ClaudeCodeConnector:
    name = "Claude Code"

    def __init__(self, executable=None, runner=None):
        self.executable = executable or shutil.which("claude")
        self.runner = runner or CommandRunner()

    def detected(self):
        if not self.executable:
            return False
        result = self.runner.run([self.executable, "--version"], timeout=10)
        return result.returncode == 0

    def status(self):
        if not self.executable:
            return "not_detected"
        result = self.runner.run(
            [self.executable, "mcp", "get", SERVER_NAME], timeout=15
        )
        return "configured" if result.returncode == 0 else "not_configured"

    def install(self, spec):
        if not self.detected():
            raise OnboardingError("Claude Code was not detected on this machine.")
        self.runner.run(
            [
                self.executable,
                "mcp",
                "remove",
                "--scope",
                "user",
                SERVER_NAME,
            ],
            timeout=15,
        )
        command = [
            self.executable,
            "mcp",
            "add",
            "--transport",
            "stdio",
            "--scope",
            "user",
            SERVER_NAME,
            "--",
            spec.command,
        ] + list(spec.args)
        result = self.runner.run(command, timeout=30)
        if result.returncode != 0:
            raise OnboardingError(
                "Claude Code could not be configured: {}".format(
                    _result_message(result)
                )
            )
        return (
            "Claude Code configured for the current user. Start a new session or "
            "open /mcp to verify it."
        )

    def remove(self):
        if not self.executable:
            raise OnboardingError("Claude Code was not detected on this machine.")
        result = self.runner.run(
            [
                self.executable,
                "mcp",
                "remove",
                "--scope",
                "user",
                SERVER_NAME,
            ],
            timeout=15,
        )
        if result.returncode != 0:
            raise OnboardingError(_result_message(result))
        return "QGIS MCP was removed from Claude Code."


def universal_config(spec):
    return json.dumps(
        {"mcpServers": {SERVER_NAME: spec.mcp_server()}},
        ensure_ascii=False,
        indent=2,
    )


def health_check(spec, timeout=15, event_pump=None):
    messages = [
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2025-06-18",
                "capabilities": {},
                "clientInfo": {"name": "qgis-onboarding", "version": "0.4.2"},
            },
        },
        {
            "jsonrpc": "2.0",
            "method": "notifications/initialized",
            "params": {},
        },
        {
            "jsonrpc": "2.0",
            "id": 2,
            "method": "tools/call",
            "params": {
                "name": "qgis_session_snapshot",
                "arguments": {"detail": "summary"},
            },
        },
    ]
    payload = "".join(json.dumps(item, separators=(",", ":")) + "\n" for item in messages)
    result = CommandRunner().run(
        spec.command_line(),
        input_text=payload,
        timeout=timeout,
        event_pump=event_pump,
    )
    if result.returncode != 0:
        raise OnboardingError(
            "The MCP health check failed: {}".format(_result_message(result))
        )
    responses = []
    for line in result.stdout.splitlines():
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(message, dict):
            responses.append(message)
    response = next((item for item in responses if item.get("id") == 2), None)
    if response is None:
        raise OnboardingError("The MCP server did not return the QGIS test response.")
    if "error" in response:
        raise OnboardingError(
            "QGIS rejected the test request: {}".format(
                response["error"].get("message", response["error"])
            )
        )
    structured = response.get("result", {}).get("structuredContent", {})
    if "revision" not in structured:
        raise OnboardingError("The MCP response did not contain a QGIS session revision.")
    return {
        "revision": structured["revision"],
        "layer_count": structured.get("project", {}).get("layer_count", 0),
    }


def _update_codex_config(path, block):
    path.parent.mkdir(parents=True, exist_ok=True)
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    without_managed = _remove_managed_block(text)
    section = re.compile(r"(?m)^\s*\[mcp_servers\.(?:\"qgis\"|qgis)\]\s*$")
    if section.search(without_managed):
        raise OnboardingError(
            "Codex already contains a QGIS MCP configuration that was not created "
            "by this plugin. Remove or rename that entry before connecting."
        )
    updated = without_managed.rstrip()
    if updated:
        updated += "\n\n"
    updated += block + "\n"
    if updated != text:
        _backup_and_write(path, updated)


def _remove_managed_block(text):
    pattern = re.compile(
        r"(?ms)^[ \t]*"
        + re.escape(MANAGED_BEGIN)
        + r"\s*$.*?^[ \t]*"
        + re.escape(MANAGED_END)
        + r"\s*$\n?"
    )
    return pattern.sub("", text)


def _backup_and_write(path, text):
    if path.is_file():
        backup = path.with_name(
            "{}.qgis-mcp-{}.bak".format(path.name, time.strftime("%Y%m%d-%H%M%S"))
        )
        shutil.copy2(str(path), str(backup))
    _atomic_write(path, text)


def _atomic_write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=path.name + "-", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, str(path))
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def _toml_string(value):
    return json.dumps(str(value), ensure_ascii=False)


def _result_message(result):
    return (result.stderr or result.stdout or "unknown error").strip()
